
env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - next/core-web-vitals
  - prettier
plugins:
  - react
  - import
  - unused-imports
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: warn
  default-case: error
  func-names: off
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react/display-name: off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': off
  "unused-imports/no-unused-imports": error
overrides:
  - files:
    - 'src/**/*.{js,jsx,ts,tsx}'
    rules:
      'import/order':
        - error
        - groups:
          - "builtin"
          - 'external'
          - 'parent'
          - 'sibling'
          - 'index'
          - 'object'
          - 'type'
          pathGroups:
            - pattern: '@/types/**'
              group: 'type'
              position: 'before'
          newlines-between: 'always'

