import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Toaster } from '@/components/ui/toaster'

import './globals.css'
import Providers from '@/components/providers'
import Header from '@/features/header/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col">
            <Header />
            <div>{children}</div>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
